### ISSUE TITLE
Link in range is dead

### ISSUE THREAD

**Issue by non-bin** [Dakkers/OpenCL-examples#4]
The link to [https://github.com/Dakkers/OpenCL-examples/blob/master/simpleopencl.blogspot.ca/2013/06/tutorial-simple-start-with-opencl-and-c.html](https://github.com/Dakkers/OpenCL-examples/blob/master/simpleopencl.blogspot.ca/2013/06/tutorial-simple-start-with-opencl-and-c.html) in example 1 is dead

**Comment by Dakkers** [comment]
updated - intended link wasn't broken, my markdown was just invalid. thank you for pointing it out!
